apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: GetListCreateRole
  namespace: test
rules:
  - apiGroups: [""]
    verbs: ["get","list","create"]
    resources:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: GetListRole
  namespace: production
