apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: SeniorAllResource
subjects:
  - kind: Group
    name: senior
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: SeniorRole2