apiVersion: v1
kind: Pod
metadata:
  name: sezer
  labels:
    name: myapp
spec:
  containers:
  
  - name: nginsite
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/source/nginx/html
        name: deneme1
  volumes:
    - name: deneme1
      hostPath:
        path: /home

  
