apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: sezer2

rules:
  - apiGroups:
      - ""
    verbs:
      - list
      - get
      - watch
    resources: 
      - pods
      - persistentvolumes
      - nodes