apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sezer2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  selector:
    matchExpressions:
      - key: sezer
        operator: In
        values:
          - baba
      