apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  parallelism: 2
  completions: 10
  backoffLimit: 5
  activeDeadlineSeconds: 100
  template:
    spec:
      containers:
      - name: sezer
        image: ubuntu
        command: ["echo","sezer"]
      restartPolicy: Never #OnFailure 